# Generated by Django 5.2.7 on 2025-10-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_answer_choice_poll_question_response_delete_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='polls/'),
        ),
    ]
