# Generated by Django 5.2.7 on 2025-11-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='polls/'),
        ),
    ]
