# Generated by Django 5.2.7 on 2026-02-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model_poll", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cedula",
            field=models.CharField(
                blank=True,
                help_text="Cédula de identidad",
                max_length=9,
                null=True,
                unique=True,
            ),
        ),
    ]
