# Generated by Django 5.2.7 on 2026-02-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_poll', '0002_user_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_public',
            field=models.BooleanField(default=True, help_text='True=Pública (usuarios), False=Interna (trabajadores)'),
        ),
    ]
