# Generated by Django 5.2.7 on 2025-11-24 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model_poll", "0002_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="end_date",
            field=models.DateTimeField(
                help_text="Fecha y hora de finalización de la encuesta"
            ),
        ),
        migrations.AlterField(
            model_name="poll",
            name="star_date",
            field=models.DateTimeField(
                help_text="Fecha y hora de inicio de la encuesta"
            ),
        ),
        migrations.CreateModel(
            name="SiteContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("HOME_IMAGE", "Imagen de Inicio"),
                            ("ABOUT_IMAGE", "Imagen de Acerca de"),
                            ("CAROUSEL_SLIDE", "Slide del Carousel"),
                            ("LIVE_STREAM", "Enlace de Transmisión en Vivo"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Título o descripción del contenido", max_length=200
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="content/"),
                ),
                (
                    "link_url",
                    models.URLField(
                        blank=True, help_text="URL de redirección (opcional)", null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Descripción adicional", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Orden de visualización"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contenido del Sitio",
                "verbose_name_plural": "Contenidos del Sitio",
                "ordering": ["content_type", "order"],
            },
        ),
    ]
