# Generated by Django 5.2.7 on 2025-11-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model_poll", "0003_alter_poll_end_date_alter_poll_star_date_sitecontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="end_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora de finalización de la encuesta",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="poll",
            name="star_date",
            field=models.DateTimeField(
                blank=True, help_text="Fecha y hora de inicio de la encuesta", null=True
            ),
        ),
    ]
