# Generated by Django 5.2.7 on 2026-02-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_poll', '0003_poll_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='rating_stars',
            field=models.IntegerField(blank=True, help_text='Número de estrellas para calificación (3-10)', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='scale_max',
            field=models.IntegerField(blank=True, help_text='Máximo para escala lineal (2-10)', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='scale_min',
            field=models.IntegerField(blank=True, help_text='Mínimo para escala lineal (0 o 1)', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SELECCION_MULTIPLE', 'Selección Múltiple (Radio)'), ('CASILLA_VERIFICACION', 'Casilla de Verificación (Checkbox)'), ('ESCALA_LINEAL', 'Escala Lineal'), ('CALIFICACION', 'Calificación (Estrellas)')], max_length=50),
        ),
    ]
