# Generated by Django 5.2.7 on 2026-02-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_poll', '0004_question_rating_stars_question_scale_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='scale_max_label',
            field=models.CharField(blank=True, help_text='Etiqueta opcional para máximo', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='scale_min_label',
            field=models.CharField(blank=True, help_text='Etiqueta opcional para mínimo', max_length=100, null=True),
        ),
    ]
