# Generated by Django 5.2.7 on 2026-03-03 20:04

import model_poll.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_poll', '0005_question_scale_max_label_question_scale_min_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=model_poll.models.content_upload_path),
        ),
    ]
